### ISSUE TITLE
Change request： Change repository name

### ISSUE THREAD

**Issue by dtlnor** [catppuccin/stable-diffusion-webui#11]
it makes lots of confuse when citing this extension, it would be much much better if this fantastic extension could have its own repo name. (`Catppuccin-for-sd-webui` etc...)

**Comment by Kettukaa** [comment]
Thanks for the issue. Yeah this is a known problem I've been trying to resolve [directly with webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7539#issue-1571127595), but they haven't implemented this yet, and several people have made a complaint about the naming, so I will probably end up just changing the name of the repo.

**Comment by Kettukaa** [comment]
Hey @nekowinston, could you do me a favor and change the name of this repo to `catppuccin-theme-sd-webui`? Thanks :)

**Comment by Kettukaa** [comment]
@dtlnor It seems like not changing the names of repos is a very enforced rule of the Catppuccin org :/ I am working with people from Webui to implement my other fix.
