### ISSUE TITLE
How do i delete Catpuccin Theme?

### ISSUE THREAD

**Issue by santaonholidays** [catppuccin/stable-diffusion-webui#16]
Question above

**Comment by isabelroses** [comment]
I'm pretty sure you can just go into the "extensions" folder. But i know for sure you can delete the directory manually from the extensions folder.

**Comment by Kettukaa** [comment]
Hey sorry, we've been trying to make this easier and have faced a few road blocks. The main issue is that the theme is downloaded as "stable-diffusion-webui". So if you go into your extensions folder and delete the folder labeled "stable-diffusion-webui" then the theme should be removed.
