### ISSUE TITLE
[Feature Request] Needs an update after recent WebUI update

### ISSUE THREAD

**Issue by younyokel** [catppuccin/stable-diffusion-webui#18]
The last webui commit updated the lists and textbox buttons in Firefox to support dark mode. I think it may have been an update from gradio or something like that. I request an update of this repository

**Comment by Kettukaa** [comment]
A1111 started using a whole new system for theming which broke a lot and requires major styling to bring back to the old layout. But @ryanccn came in to save the day and ported the theme to the new system. This will be the new base css. It doesn't look identical to the old theme, but we will go through and add back in all of the layout/coloring improvements from the previous theme over the coming days.

**Comment by shirooo39** [comment]
> A1111 started using a whole new system for theming which broke a lot and requires major styling to bring back to the old layout. But @ryanccn came in to save the day and ported the theme to the new system. This will be the new base css. It doesn't look identical to the old theme, but we will go through and add back in all of the layout/coloring improvements from the previous theme over the coming days.

I'm using this commit of the WebUI "64fc936738d296f5eb2ff495006e298c2aeb51bf" as this is the best commit that doesn't have gradio version something (I forgot), which the new gradio doesn't really work well on Colab and on Firefox.

can I still use this custom theme?  
the Kitchen theme specifically mentioned that they require latest commit of the WebUI...

**Comment by Kettukaa** [comment]
> > A1111 started using a whole new system for theming which broke a lot and requires major styling to bring back to the old layout. But @ryanccn came in to save the day and ported the theme to the new system. This will be the new base css. It doesn't look identical to the old theme, but we will go through and add back in all of the layout/coloring improvements from the previous theme over the coming days.
> 
> I'm using this commit of the WebUI "64fc936738d296f5eb2ff495006e298c2aeb51bf" as this is the best commit that doesn't have gradio version something (I forgot), which the new gradio doesn't really work well on Colab and on Firefox.
> 
> can I still use this custom theme? the Kitchen theme specifically mentioned that they require latest commit of the WebUI...

Most recent updates solved this. Please let me know if there is any more issues!
