### ISSUE TITLE
the dropdown menus dont get applied

### ISSUE THREAD

**Issue by Ghudza** [catppuccin/stable-diffusion-webui#4]
as the title says, the dropdown menus all of them don't get the same colour palette but a blinding white

**Comment by Kettukaa** [comment]
Thanks for posting an issue! Can you update the extension and let me know if it is still happening? It is not happening for me after the latest update. If it is still happening, let me know what browser you're using.

**Comment by Dreamz-Dziner** [comment]
Yes. Same for me. I installed from the extension tab couple of mins ago and tried changing every color in the theme but the drop down is white which makes the text unreadable.

**Comment by Kettukaa** [comment]
Oh ok I see. The dropdown is unthemed and being colored by the browser. My firefox is catppuccin themed, which is why I reckon I didn't have an issue. I will quickly fix this.

**Comment by Dreamz-Dziner** [comment]
No problem:-)Thank you for this awesome extension!

**Comment by Kettukaa** [comment]
Alrighty I think the latest update resolves this issue. If the problem persists then feel free to reopen this issue and let me know what browser you're all using :)
