### ISSUE TITLE
Could you help me uninstall it?

### ISSUE THREAD

**Issue by uvarient** [catppuccin/stable-diffusion-webui#8]
I don't understand what you mean
Open user.css and set the variavble --accent: var(--{preferred color});

**Comment by Kettukaa** [comment]
Hey, I'm not sure what you're looking for here. Do you want to uninstall the theme, or change the preferred color? 

If you're looking to uninstall the theme then that can be done multiple ways depending on how you installed it. If you just downloaded the user.css, then simply delete it. If you installed the extension then you can delete the folder `stable-diffusion-webui/extensions/stable-diffusion-webui/` 

If you're looking on changing the preferred accent color, then there is also two ways you can do that. If you only downloaded the user.css, then you just need to open the file and change the `--accent: var(...);` line to have any of the accent colors defined above it. For instance, using `--accent: var(--maroon);` will set it to maroon.  If you downloaded the theme as an extension, then you can go to the webui settings, click on Catppuccin on the side, and select your accent color there.  

Let me know if you have any other problems.

**Comment by Kettukaa** [comment]
Feel free to open this back up if you're still having issues. I will be closing this for now.
