### ISSUE TITLE
Support for custom favicon

### ISSUE THREAD

**Issue by Dragoy** [catppuccin/stable-diffusion-webui#9]
First of all, I would like to thank the creators for such a great design theme, it makes the interface look really fresh. 
Could you add custom branded favion for this theme or tell me how to change them manually, I would be very grateful.

**Comment by Kettukaa** [comment]
Thanks! If you like this theme, then you should check out the many [other Catppuccin ports](https://github.com/catppuccin/catppuccin) we have.   

With regards to custom favicon, I'm not sure if it is possible to do using just CSS. I can definitely look into other methods, but it isn't planned for the time being. 

I will set this as "not planned" for now, but I will look back into it when I make the next major change to the theme. 

Feel free to open another issue if you have another idea or notice a bug.
